### ISSUE TITLE
My new life calculator conflicts with this on Google Assistant

### ISSUE THREAD

**Issue by kasplat** [jacksonrayhamilton/yugiohcalculator#1]
Hi! I made a Yugioh Life Calculator that can calculate life entirely with your voice: https://github.com/kasplat/Yugioh-Life-calculator

It's really rudimentary now, but it works pretty well. I found out that if I tell google to "Talk to Yu-Gi-Oh Calculator", it actually redirects to the yugiohcalculator.com website, but if you say "Talk to Yugioh Calculator", it starts my voice app. I don't know if this was intentional, but I wanted to figure out what the best course of action to allow both applications to exist (since they're quite different) is. I was thinking perhaps I could use the Yu-Gi-Oh! calculator invocation, and then have a suggestion upon loading the app to open your website so that invocations of Yugioh and Yu-Gi-Oh are consistent.

I'm open to any solutions! If I don't hear anything in a few days, I'll go ahead and implement the solution I suggested.

**Comment by jacksonrayhamilton** [comment]
Interesting.  I am not familiar Google Voice Assistant.  Are you saying that it associates the voice command “Yu-Gi-Oh”—that is, the phrase “yoo dash gee dash oh”—with my app, and the phrase “yoogeeoh” with yours?

Since your app involves voice and mine does not, it seems like it would be ideal if the phrase “talk to yoogeeoh calculator” would open your app, and the phrase “open yoogeeoh calculator” or “open yoogeeoh calculator dot com” would open my app.  Is that possible?

If not, then feel free to use the phrase “yoo dash gee dash oh calculator” and “yoogeeoh calculator” for your app however you’d like.  I don’t mind if Google Voice Assistant doesn’t know about my app.

**Comment by kasplat** [comment]
1) That was the behavior when I tested on Friday, but I can't replicate it right now.

2) It shouldn't be possible since google invocations are done with "Talk to [app name]" unfortunately.

3) Sounds good! I don't really know how it was opening your app in the first place if you didn't define that behavior, that's interesting. Thank you!
